apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Welcome to Rini's App</h1>
      <p>This is the landing page</p>
    </body>
    </html>
