apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user: cm9vdA==             # base64 for "root"
  mysql-password: bXlzcWw=         # base64 for "mysql"
  mysql-database: dGVzdGRi         # base64 for "testdb"
